# Create a new page. All non-optional fields must be provided:
#   content, description, editor, isPublished, isPrivate, locale, path, title
# Optional: publishStartDate, publishEndDate, scriptCss, scriptJs, tags
mutation(
  $content: String!
  $description: String!
  $editor: String!
  $isPublished: Boolean!
  $isPrivate: Boolean!
  $locale: String!
  $path: String!
  $title: String!
  $tags: [String]!
  $publishStartDate: Date
  $publishEndDate: Date
  $scriptCss: String
  $scriptJs: String
) {
  pages {
    create(
      content: $content
      description: $description
      editor: $editor
      isPublished: $isPublished
      isPrivate: $isPrivate
      locale: $locale
      path: $path
      title: $title
      tags: $tags
      publishStartDate: $publishStartDate
      publishEndDate: $publishEndDate
      scriptCss: $scriptCss
      scriptJs: $scriptJs
    ) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
      page {
        id
        path
        title
        createdAt
        updatedAt
      }
    }
  }
}
