# Create a new asset folder under a parent folder.
# Requires manage:system or write:assets scope.
mutation($parentFolderId: Int!, $slug: String!, $name: String) {
  assets {
    createFolder(parentFolderId: $parentFolderId, slug: $slug, name: $name) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
