# Rebuild the search index after bulk updates.
# Requires manage:system scope.
mutation {
  search {
    rebuildIndex {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
