#!/usr/bin/env bash
# scheduler-run.sh — execute one scheduled Pi task and persist a diagnostic record.
# The task definition is a base64-encoded JSON object generated by scheduler.ts.
set -euo pipefail

WORKSPACE="/workspace"
HISTORY_DIR="$WORKSPACE/.pi-web/scheduler"
RUNS_DIR="$HISTORY_DIR/runs"
HISTORY_FILE="$HISTORY_DIR/history.jsonl"
MAX_RUNS="${SCHEDULER_HISTORY_MAX_RUNS:-200}"

log() { echo "[scheduler-run] $*" >&2; }

if [[ $# -ne 1 ]]; then
    log "expected one encoded task definition"
    exit 64
fi

task_json="$(printf '%s' "$1" | base64 --decode 2>/dev/null)" || {
    log "could not decode task definition"
    exit 64
}

task_name="$(jq -r '.name // empty' <<<"$task_json")"
if [[ -z "$task_name" ]]; then
    log "task definition has no name"
    exit 64
fi

safe_name="$(tr -cs '[:alnum:].-_' '-' <<<"$task_name" | sed 's/^-//; s/-$//')"
run_id="$(date -u +%Y%m%dT%H%M%SZ)-${safe_name:-task}-$(od -An -N3 -tx1 /dev/urandom | tr -d ' \n')"
run_dir="$RUNS_DIR/$run_id"
stdout_file="$run_dir/stdout.log"
stderr_file="$run_dir/stderr.log"
metadata_file="$run_dir/metadata.json"
started_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
started_ms="$(date +%s%3N)"

mkdir -p "$run_dir"
chmod 0700 "$HISTORY_DIR" "$RUNS_DIR" "$run_dir"

append_history() {
    # Each record is one compact JSON line. O_APPEND makes individual small writes
    # practical for concurrently scheduled jobs while preserving a human-readable index.
    printf '%s\n' "$1" >> "$HISTORY_FILE"
}

initial_record="$(jq -cn \
    --arg event "started" \
    --arg runId "$run_id" \
    --arg task "$task_name" \
    --arg startedAt "$started_at" \
    --arg stdout ".pi-web/scheduler/runs/$run_id/stdout.log" \
    --arg stderr ".pi-web/scheduler/runs/$run_id/stderr.log" \
    --argjson taskDefinition "$task_json" \
    '{event: $event, runId: $runId, task: $task, startedAt: $startedAt, stdoutPath: $stdout, stderrPath: $stderr, taskDefinition: $taskDefinition}')"
append_history "$initial_record"

mapfile -t tools < <(jq -r '.tools // "" | split(",")[] | select(length > 0)' <<<"$task_json")
mapfile -t skills < <(jq -r '.skills // "" | split(",")[] | select(length > 0)' <<<"$task_json")
model="$(jq -r '.model // empty' <<<"$task_json")"
prompt="$(jq -r '.prompt // empty' <<<"$task_json")"
prompt_file="$(jq -r '.promptFile // empty' <<<"$task_json")"
ephemeral="$(jq -r '.ephemeralSession // false' <<<"$task_json")"

if [[ -n "$prompt_file" && "$prompt_file" != /* ]]; then
    prompt_file="$WORKSPACE/$prompt_file"
fi

pi_args=(-p --approve --name "scheduled:${task_name}:${run_id}")
if [[ ${#tools[@]} -gt 0 ]]; then
    pi_args+=(--tools "$(IFS=,; echo "${tools[*]}")")
fi
for skill in "${skills[@]}"; do
    if [[ "$skill" != /* && "$skill" != .* ]]; then
        skill="$HOME/.pi/agent/skills/$skill"
    fi
    pi_args+=(--skill "$skill")
done
if [[ -n "$model" ]]; then
    pi_args+=(--model "$model")
fi
if [[ "$ephemeral" == "true" ]]; then
    pi_args+=(--no-session)
fi
if [[ -n "$prompt_file" ]]; then
    pi_args+=("@$prompt_file")
else
    pi_args+=("$prompt")
fi

set +e
(
    cd "$WORKSPACE"
    pi "${pi_args[@]}"
) >"$stdout_file" 2>"$stderr_file"
exit_code=$?
set -e

finished_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
finished_ms="$(date +%s%3N)"
duration_ms=$((finished_ms - started_ms))
status="succeeded"
if [[ $exit_code -ne 0 ]]; then
    status="failed"
fi

stderr_tail="$(tail -c 4096 "$stderr_file" 2>/dev/null || true)"
classification=""
if [[ $exit_code -ne 0 ]]; then
    if grep -Eqi '401|403|authentication|api key|unauthori[sz]ed' <<<"$stderr_tail"; then
        classification="authentication"
    elif grep -Eqi '429|rate limit|quota' <<<"$stderr_tail"; then
        classification="rate-limit"
    elif grep -Eqi 'proxy|dns|ENOTFOUND|ECONNREFUSED|network' <<<"$stderr_tail"; then
        classification="network"
    elif grep -Eqi 'not found|ENOENT|permission denied|EACCES' <<<"$stderr_tail"; then
        classification="environment"
    else
        classification="agent-or-provider"
    fi
fi

final_record="$(jq -cn \
    --arg event "completed" \
    --arg runId "$run_id" \
    --arg task "$task_name" \
    --arg status "$status" \
    --arg startedAt "$started_at" \
    --arg finishedAt "$finished_at" \
    --arg stdout ".pi-web/scheduler/runs/$run_id/stdout.log" \
    --arg stderr ".pi-web/scheduler/runs/$run_id/stderr.log" \
    --arg classification "$classification" \
    --arg stderrTail "$stderr_tail" \
    --argjson exitCode "$exit_code" \
    --argjson durationMs "$duration_ms" \
    --argjson taskDefinition "$task_json" \
    '{event: $event, runId: $runId, task: $task, status: $status, startedAt: $startedAt, finishedAt: $finishedAt, durationMs: $durationMs, exitCode: $exitCode, classification: $classification, stderrTail: $stderrTail, stdoutPath: $stdout, stderrPath: $stderr, taskDefinition: $taskDefinition}')"
printf '%s\n' "$final_record" > "$metadata_file"
append_history "$final_record"

# Retain the most recent completed run directories. History remains append-only;
# the UI ignores records whose log directory was pruned.
if [[ "$MAX_RUNS" =~ ^[0-9]+$ ]] && (( MAX_RUNS > 0 )); then
    mapfile -t old_runs < <(find "$RUNS_DIR" -mindepth 1 -maxdepth 1 -type d -printf '%T@ %p\n' | sort -nr | awk -v max="$MAX_RUNS" 'NR > max { print $2 }')
    for old_run in "${old_runs[@]}"; do
        rm -rf -- "$old_run"
    done
fi

exit "$exit_code"